# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4d17892fffb5b35b56efbc470693e9e66e60d5424542af67523720c5da16f8117480849281113ab4dea7c43f66eee0198f7d1dab087f257584a4aacf692973ac

test:
  secret_key_base: 2ccd8be629317b9f8aa4b4b21ec429fe2acbb482ec3575b3e804bfac42184c03ffd20506ad99a620aadf181368266c27c2baa2c39985940c9d218fed2d14d94b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
